# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MRTestProduct' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MRTestProduct

  target 'MRTestProductTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MRTestProductUITests' do
    # Pods for testing
  end

end
